# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'network_calc.ui'
#
# Created: Mon Nov 17 20:38:01 2014
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_NetworkCalcDialog(object):
    def setupUi(self, NetworkCalcDialog):
        NetworkCalcDialog.setObjectName(_fromUtf8("NetworkCalcDialog"))
        NetworkCalcDialog.resize(641, 549)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NetworkCalcDialog.sizePolicy().hasHeightForWidth())
        NetworkCalcDialog.setSizePolicy(sizePolicy)
        NetworkCalcDialog.setMinimumSize(QtCore.QSize(641, 549))
        NetworkCalcDialog.setMaximumSize(QtCore.QSize(641, 549))
        NetworkCalcDialog.setWindowTitle(_fromUtf8("Network Adjustment"))
        NetworkCalcDialog.setAccessibleName(_fromUtf8(""))
        NetworkCalcDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.Points_GroupBox = QtGui.QGroupBox(NetworkCalcDialog)
        self.Points_GroupBox.setGeometry(QtCore.QRect(10, 10, 401, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Points_GroupBox.sizePolicy().hasHeightForWidth())
        self.Points_GroupBox.setSizePolicy(sizePolicy)
        self.Points_GroupBox.setObjectName(_fromUtf8("Points_GroupBox"))
        self.Points_ListView = QtGui.QListView(self.Points_GroupBox)
        self.Points_ListView.setGeometry(QtCore.QRect(20, 40, 121, 261))
        self.Points_ListView.setObjectName(_fromUtf8("Points_ListView"))
        self.AddFix_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.AddFix_PushButton.setGeometry(QtCore.QRect(160, 50, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddFix_PushButton.sizePolicy().hasHeightForWidth())
        self.AddFix_PushButton.setSizePolicy(sizePolicy)
        self.AddFix_PushButton.setObjectName(_fromUtf8("AddFix_PushButton"))
        self.AddAdj_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.AddAdj_PushButton.setGeometry(QtCore.QRect(160, 200, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddAdj_PushButton.sizePolicy().hasHeightForWidth())
        self.AddAdj_PushButton.setSizePolicy(sizePolicy)
        self.AddAdj_PushButton.setObjectName(_fromUtf8("AddAdj_PushButton"))
        self.FixPoints_ListView = QtGui.QListView(self.Points_GroupBox)
        self.FixPoints_ListView.setGeometry(QtCore.QRect(260, 40, 121, 111))
        self.FixPoints_ListView.setObjectName(_fromUtf8("FixPoints_ListView"))
        self.RemoveFix_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.RemoveFix_PushButton.setGeometry(QtCore.QRect(160, 90, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveFix_PushButton.sizePolicy().hasHeightForWidth())
        self.RemoveFix_PushButton.setSizePolicy(sizePolicy)
        self.RemoveFix_PushButton.setObjectName(_fromUtf8("RemoveFix_PushButton"))
        self.ListPoints_Label = QtGui.QLabel(self.Points_GroupBox)
        self.ListPoints_Label.setGeometry(QtCore.QRect(20, 20, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ListPoints_Label.sizePolicy().hasHeightForWidth())
        self.ListPoints_Label.setSizePolicy(sizePolicy)
        self.ListPoints_Label.setObjectName(_fromUtf8("ListPoints_Label"))
        self.FixPoints_Label = QtGui.QLabel(self.Points_GroupBox)
        self.FixPoints_Label.setGeometry(QtCore.QRect(260, 20, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FixPoints_Label.sizePolicy().hasHeightForWidth())
        self.FixPoints_Label.setSizePolicy(sizePolicy)
        self.FixPoints_Label.setObjectName(_fromUtf8("FixPoints_Label"))
        self.RemoveAdj_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.RemoveAdj_PushButton.setGeometry(QtCore.QRect(160, 240, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveAdj_PushButton.sizePolicy().hasHeightForWidth())
        self.RemoveAdj_PushButton.setSizePolicy(sizePolicy)
        self.RemoveAdj_PushButton.setObjectName(_fromUtf8("RemoveAdj_PushButton"))
        self.AdjPoints_ListView = QtGui.QListView(self.Points_GroupBox)
        self.AdjPoints_ListView.setGeometry(QtCore.QRect(260, 190, 121, 111))
        self.AdjPoints_ListView.setObjectName(_fromUtf8("AdjPoints_ListView"))
        self.AdjPoints_Label = QtGui.QLabel(self.Points_GroupBox)
        self.AdjPoints_Label.setGeometry(QtCore.QRect(260, 170, 141, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AdjPoints_Label.sizePolicy().hasHeightForWidth())
        self.AdjPoints_Label.setSizePolicy(sizePolicy)
        self.AdjPoints_Label.setObjectName(_fromUtf8("AdjPoints_Label"))
        self.Reset_PushButton = QtGui.QPushButton(NetworkCalcDialog)
        self.Reset_PushButton.setGeometry(QtCore.QRect(440, 510, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset_PushButton.sizePolicy().hasHeightForWidth())
        self.Reset_PushButton.setSizePolicy(sizePolicy)
        self.Reset_PushButton.setObjectName(_fromUtf8("Reset_PushButton"))
        self.Close_PushButton = QtGui.QPushButton(NetworkCalcDialog)
        self.Close_PushButton.setGeometry(QtCore.QRect(540, 510, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Close_PushButton.sizePolicy().hasHeightForWidth())
        self.Close_PushButton.setSizePolicy(sizePolicy)
        self.Close_PushButton.setObjectName(_fromUtf8("Close_PushButton"))
        self.Result_GroupBox = QtGui.QGroupBox(NetworkCalcDialog)
        self.Result_GroupBox.setGeometry(QtCore.QRect(10, 330, 621, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result_GroupBox.sizePolicy().hasHeightForWidth())
        self.Result_GroupBox.setSizePolicy(sizePolicy)
        self.Result_GroupBox.setObjectName(_fromUtf8("Result_GroupBox"))
        self.Result_TextBrowser = QtGui.QTextBrowser(self.Result_GroupBox)
        self.Result_TextBrowser.setGeometry(QtCore.QRect(10, 20, 601, 131))
        self.Result_TextBrowser.setObjectName(_fromUtf8("Result_TextBrowser"))
        self.Help_PushButton = QtGui.QPushButton(NetworkCalcDialog)
        self.Help_PushButton.setGeometry(QtCore.QRect(20, 510, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Help_PushButton.sizePolicy().hasHeightForWidth())
        self.Help_PushButton.setSizePolicy(sizePolicy)
        self.Help_PushButton.setObjectName(_fromUtf8("Help_PushButton"))
        self.Calculate_PushButton = QtGui.QPushButton(NetworkCalcDialog)
        self.Calculate_PushButton.setGeometry(QtCore.QRect(340, 510, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Calculate_PushButton.sizePolicy().hasHeightForWidth())
        self.Calculate_PushButton.setSizePolicy(sizePolicy)
        self.Calculate_PushButton.setObjectName(_fromUtf8("Calculate_PushButton"))
        self.Parameters_GroupBox = QtGui.QGroupBox(NetworkCalcDialog)
        self.Parameters_GroupBox.setGeometry(QtCore.QRect(430, 10, 201, 311))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Parameters_GroupBox.sizePolicy().hasHeightForWidth())
        self.Parameters_GroupBox.setSizePolicy(sizePolicy)
        self.Parameters_GroupBox.setObjectName(_fromUtf8("Parameters_GroupBox"))
        self.ConfLevel_ComboBox = QtGui.QComboBox(self.Parameters_GroupBox)
        self.ConfLevel_ComboBox.setGeometry(QtCore.QRect(30, 260, 81, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfLevel_ComboBox.sizePolicy().hasHeightForWidth())
        self.ConfLevel_ComboBox.setSizePolicy(sizePolicy)
        self.ConfLevel_ComboBox.setObjectName(_fromUtf8("ConfLevel_ComboBox"))
        self.ConfLevel_ComboBox.addItem(_fromUtf8(""))
        self.ConfLevel_ComboBox.addItem(_fromUtf8(""))
        self.ConfLevel_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.ConfLevel_Label.setGeometry(QtCore.QRect(10, 240, 151, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConfLevel_Label.sizePolicy().hasHeightForWidth())
        self.ConfLevel_Label.setSizePolicy(sizePolicy)
        self.ConfLevel_Label.setObjectName(_fromUtf8("ConfLevel_Label"))
        self.TavmeresDevMM_ComboBox = QtGui.QComboBox(self.Parameters_GroupBox)
        self.TavmeresDevMM_ComboBox.setGeometry(QtCore.QRect(30, 150, 81, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TavmeresDevMM_ComboBox.sizePolicy().hasHeightForWidth())
        self.TavmeresDevMM_ComboBox.setSizePolicy(sizePolicy)
        self.TavmeresDevMM_ComboBox.setObjectName(_fromUtf8("TavmeresDevMM_ComboBox"))
        self.TavmeresDevMM_ComboBox.addItem(_fromUtf8(""))
        self.TavmeresDev_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.TavmeresDev_Label.setGeometry(QtCore.QRect(10, 120, 161, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TavmeresDev_Label.sizePolicy().hasHeightForWidth())
        self.TavmeresDev_Label.setSizePolicy(sizePolicy)
        self.TavmeresDev_Label.setObjectName(_fromUtf8("TavmeresDev_Label"))
        self.TavmeresDevMMKM_ComboBox = QtGui.QComboBox(self.Parameters_GroupBox)
        self.TavmeresDevMMKM_ComboBox.setGeometry(QtCore.QRect(30, 190, 81, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TavmeresDevMMKM_ComboBox.sizePolicy().hasHeightForWidth())
        self.TavmeresDevMMKM_ComboBox.setSizePolicy(sizePolicy)
        self.TavmeresDevMMKM_ComboBox.setObjectName(_fromUtf8("TavmeresDevMMKM_ComboBox"))
        self.TavmeresDevMMKM_ComboBox.addItem(_fromUtf8(""))
        self.TavmeresDevMM_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.TavmeresDevMM_Label.setGeometry(QtCore.QRect(120, 160, 61, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TavmeresDevMM_Label.sizePolicy().hasHeightForWidth())
        self.TavmeresDevMM_Label.setSizePolicy(sizePolicy)
        self.TavmeresDevMM_Label.setObjectName(_fromUtf8("TavmeresDevMM_Label"))
        self.TavmeresDevMMKM_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.TavmeresDevMMKM_Label.setGeometry(QtCore.QRect(120, 200, 61, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TavmeresDevMMKM_Label.sizePolicy().hasHeightForWidth())
        self.TavmeresDevMMKM_Label.setSizePolicy(sizePolicy)
        self.TavmeresDevMMKM_Label.setObjectName(_fromUtf8("TavmeresDevMMKM_Label"))
        self.IranymeresDev_ComboBox = QtGui.QComboBox(self.Parameters_GroupBox)
        self.IranymeresDev_ComboBox.setGeometry(QtCore.QRect(30, 70, 81, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IranymeresDev_ComboBox.sizePolicy().hasHeightForWidth())
        self.IranymeresDev_ComboBox.setSizePolicy(sizePolicy)
        self.IranymeresDev_ComboBox.setObjectName(_fromUtf8("IranymeresDev_ComboBox"))
        self.IranymeresDev_ComboBox.addItem(_fromUtf8(""))
        self.IranymeresDev_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.IranymeresDev_Label.setGeometry(QtCore.QRect(10, 30, 161, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IranymeresDev_Label.sizePolicy().hasHeightForWidth())
        self.IranymeresDev_Label.setSizePolicy(sizePolicy)
        self.IranymeresDev_Label.setObjectName(_fromUtf8("IranymeresDev_Label"))
        self.ZenitDev_Label = QtGui.QLabel(self.Parameters_GroupBox)
        self.ZenitDev_Label.setGeometry(QtCore.QRect(10, 50, 181, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZenitDev_Label.sizePolicy().hasHeightForWidth())
        self.ZenitDev_Label.setSizePolicy(sizePolicy)
        self.ZenitDev_Label.setObjectName(_fromUtf8("ZenitDev_Label"))

        self.retranslateUi(NetworkCalcDialog)
        QtCore.QMetaObject.connectSlotsByName(NetworkCalcDialog)

    def retranslateUi(self, NetworkCalcDialog):
        self.Points_GroupBox.setTitle(QtGui.QApplication.translate("NetworkCalcDialog", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.AddFix_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Add >", None, QtGui.QApplication.UnicodeUTF8))
        self.AddAdj_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Add >", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveFix_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "< Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.ListPoints_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "List of Points", None, QtGui.QApplication.UnicodeUTF8))
        self.FixPoints_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Fix Points", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveAdj_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "< Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.AdjPoints_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Adjustment Points", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_GroupBox.setTitle(QtGui.QApplication.translate("NetworkCalcDialog", "Result of Calculations", None, QtGui.QApplication.UnicodeUTF8))
        self.Help_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.Calculate_PushButton.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Parameters_GroupBox.setTitle(QtGui.QApplication.translate("NetworkCalcDialog", "Paramaters", None, QtGui.QApplication.UnicodeUTF8))
        self.ConfLevel_ComboBox.setItemText(0, QtGui.QApplication.translate("NetworkCalcDialog", "0.95", None, QtGui.QApplication.UnicodeUTF8))
        self.ConfLevel_ComboBox.setItemText(1, QtGui.QApplication.translate("NetworkCalcDialog", "0.997", None, QtGui.QApplication.UnicodeUTF8))
        self.ConfLevel_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Confidence Level", None, QtGui.QApplication.UnicodeUTF8))
        self.TavmeresDevMM_ComboBox.setItemText(0, QtGui.QApplication.translate("NetworkCalcDialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.TavmeresDev_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Távmérési deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.TavmeresDevMMKM_ComboBox.setItemText(0, QtGui.QApplication.translate("NetworkCalcDialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.TavmeresDevMM_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "[mm]", None, QtGui.QApplication.UnicodeUTF8))
        self.TavmeresDevMMKM_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "[mm/km]", None, QtGui.QApplication.UnicodeUTF8))
        self.IranymeresDev_ComboBox.setItemText(0, QtGui.QApplication.translate("NetworkCalcDialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.IranymeresDev_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Iránymérési deviation", None, QtGui.QApplication.UnicodeUTF8))
        self.ZenitDev_Label.setText(QtGui.QApplication.translate("NetworkCalcDialog", "Zenitszög mérési deviation", None, QtGui.QApplication.UnicodeUTF8))

