# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_calc.ui'
#
# Created: Sun Nov 16 23:01:43 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SimpleCalcDialog(object):
    def setupUi(self, SimpleCalcDialog):
        SimpleCalcDialog.setObjectName(_fromUtf8("SimpleCalcDialog"))
        SimpleCalcDialog.resize(744, 408)
        SimpleCalcDialog.setWindowTitle(QtGui.QApplication.translate("SimpleCalcDialog", "Simple Point Calculations", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton = QtGui.QPushButton(SimpleCalcDialog)
        self.ResetButton.setGeometry(QtCore.QRect(540, 370, 91, 23))
        self.ResetButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.CloseButton = QtGui.QPushButton(SimpleCalcDialog)
        self.CloseButton.setGeometry(QtCore.QRect(650, 370, 75, 23))
        self.CloseButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.HelpButton = QtGui.QPushButton(SimpleCalcDialog)
        self.HelpButton.setGeometry(QtCore.QRect(10, 370, 75, 23))
        self.HelpButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.HelpButton.setObjectName(_fromUtf8("HelpButton"))
        self.RadioGroup = QtGui.QGroupBox(SimpleCalcDialog)
        self.RadioGroup.setGeometry(QtCore.QRect(0, 0, 141, 211))
        self.RadioGroup.setTitle(QtGui.QApplication.translate("SimpleCalcDialog", "Calculation", None, QtGui.QApplication.UnicodeUTF8))
        self.RadioGroup.setFlat(False)
        self.RadioGroup.setCheckable(False)
        self.RadioGroup.setObjectName(_fromUtf8("RadioGroup"))
        self.OrientRadio = QtGui.QRadioButton(self.RadioGroup)
        self.OrientRadio.setGeometry(QtCore.QRect(10, 30, 151, 17))
        self.OrientRadio.setToolTip(QtGui.QApplication.translate("SimpleCalcDialog", "Calculate orientation angle  on stations", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientRadio.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.OrientRadio.setObjectName(_fromUtf8("OrientRadio"))
        self.RadialRadio = QtGui.QRadioButton(self.RadioGroup)
        self.RadialRadio.setGeometry(QtCore.QRect(10, 60, 161, 17))
        self.RadialRadio.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Radial Survey", None, QtGui.QApplication.UnicodeUTF8))
        self.RadialRadio.setObjectName(_fromUtf8("RadialRadio"))
        self.IntersectRadio = QtGui.QRadioButton(self.RadioGroup)
        self.IntersectRadio.setGeometry(QtCore.QRect(10, 90, 151, 17))
        self.IntersectRadio.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Intersection", None, QtGui.QApplication.UnicodeUTF8))
        self.IntersectRadio.setObjectName(_fromUtf8("IntersectRadio"))
        self.ResectionRadio = QtGui.QRadioButton(self.RadioGroup)
        self.ResectionRadio.setGeometry(QtCore.QRect(10, 120, 141, 17))
        self.ResectionRadio.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Resection", None, QtGui.QApplication.UnicodeUTF8))
        self.ResectionRadio.setObjectName(_fromUtf8("ResectionRadio"))
        self.FreeRadio = QtGui.QRadioButton(self.RadioGroup)
        self.FreeRadio.setGeometry(QtCore.QRect(10, 150, 141, 17))
        self.FreeRadio.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Free Station", None, QtGui.QApplication.UnicodeUTF8))
        self.FreeRadio.setObjectName(_fromUtf8("FreeRadio"))
        self.PointsGroup = QtGui.QGroupBox(SimpleCalcDialog)
        self.PointsGroup.setGeometry(QtCore.QRect(300, 0, 441, 211))
        self.PointsGroup.setTitle(QtGui.QApplication.translate("SimpleCalcDialog", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.PointsGroup.setObjectName(_fromUtf8("PointsGroup"))
        self.AddButton = QtGui.QPushButton(self.PointsGroup)
        self.AddButton.setGeometry(QtCore.QRect(140, 50, 81, 23))
        self.AddButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Add >", None, QtGui.QApplication.UnicodeUTF8))
        self.AddButton.setObjectName(_fromUtf8("AddButton"))
        self.AddAllButton = QtGui.QPushButton(self.PointsGroup)
        self.AddAllButton.setGeometry(QtCore.QRect(140, 80, 81, 23))
        self.AddAllButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Add all", None, QtGui.QApplication.UnicodeUTF8))
        self.AddAllButton.setObjectName(_fromUtf8("AddAllButton"))
        self.TargetList = QtGui.QListView(self.PointsGroup)
        self.TargetList.setGeometry(QtCore.QRect(230, 40, 121, 131))
        self.TargetList.setObjectName(_fromUtf8("TargetList"))
        self.RemoveButton = QtGui.QPushButton(self.PointsGroup)
        self.RemoveButton.setGeometry(QtCore.QRect(140, 110, 81, 23))
        self.RemoveButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "< Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveButton.setObjectName(_fromUtf8("RemoveButton"))
        self.RemoveAllButton = QtGui.QPushButton(self.PointsGroup)
        self.RemoveAllButton.setGeometry(QtCore.QRect(140, 140, 81, 23))
        self.RemoveAllButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Remove all", None, QtGui.QApplication.UnicodeUTF8))
        self.RemoveAllButton.setObjectName(_fromUtf8("RemoveAllButton"))
        self.label_9 = QtGui.QLabel(self.PointsGroup)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.label_9.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Target Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.PointsGroup)
        self.label_10.setGeometry(QtCore.QRect(230, 20, 121, 16))
        self.label_10.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Used Points", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.SourceList = QtGui.QListView(self.PointsGroup)
        self.SourceList.setGeometry(QtCore.QRect(10, 40, 121, 131))
        self.SourceList.setObjectName(_fromUtf8("SourceList"))
        self.ResultGroup = QtGui.QGroupBox(SimpleCalcDialog)
        self.ResultGroup.setGeometry(QtCore.QRect(0, 180, 741, 201))
        self.ResultGroup.setTitle(QtGui.QApplication.translate("SimpleCalcDialog", "Result of Calculations", None, QtGui.QApplication.UnicodeUTF8))
        self.ResultGroup.setObjectName(_fromUtf8("ResultGroup"))
        self.TextBrowser = QtGui.QTextBrowser(self.ResultGroup)
        self.TextBrowser.setEnabled(False)
        self.TextBrowser.setGeometry(QtCore.QRect(10, 20, 721, 161))
        self.TextBrowser.setObjectName(_fromUtf8("TextBrowser"))
        self.StationGroup = QtGui.QGroupBox(SimpleCalcDialog)
        self.StationGroup.setGeometry(QtCore.QRect(150, 0, 141, 211))
        self.StationGroup.setTitle(QtGui.QApplication.translate("SimpleCalcDialog", "Station", None, QtGui.QApplication.UnicodeUTF8))
        self.StationGroup.setObjectName(_fromUtf8("StationGroup"))
        self.Station1Combo = QtGui.QComboBox(self.StationGroup)
        self.Station1Combo.setGeometry(QtCore.QRect(10, 50, 121, 22))
        self.Station1Combo.setObjectName(_fromUtf8("Station1Combo"))
        self.label_7 = QtGui.QLabel(self.StationGroup)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_7.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Station (1)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.StationGroup)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 71, 16))
        self.label_8.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Station (2)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Station2Combo = QtGui.QComboBox(self.StationGroup)
        self.Station2Combo.setGeometry(QtCore.QRect(10, 120, 121, 22))
        self.Station2Combo.setObjectName(_fromUtf8("Station2Combo"))
        self.CalcButton = QtGui.QPushButton(SimpleCalcDialog)
        self.CalcButton.setGeometry(QtCore.QRect(450, 370, 75, 23))
        self.CalcButton.setText(QtGui.QApplication.translate("SimpleCalcDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.CalcButton.setObjectName(_fromUtf8("CalcButton"))

        self.retranslateUi(SimpleCalcDialog)
        QtCore.QMetaObject.connectSlotsByName(SimpleCalcDialog)

    def retranslateUi(self, SimpleCalcDialog):
        pass

