# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traverse_calc.ui'
#
# Created: Tue Nov 11 19:08:50 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_TraverseCalcDialog(object):
    def setupUi(self, TraverseCalcDialog):
        TraverseCalcDialog.setObjectName(_fromUtf8("TraverseCalcDialog"))
        TraverseCalcDialog.resize(790, 435)
        TraverseCalcDialog.setWindowTitle(_fromUtf8("Traverse Calculations"))
        TraverseCalcDialog.setAccessibleName(_fromUtf8(""))
        TraverseCalcDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.Endpoints_GroupBox = QtGui.QGroupBox(TraverseCalcDialog)
        self.Endpoints_GroupBox.setGeometry(QtCore.QRect(210, 10, 151, 211))
        self.Endpoints_GroupBox.setTitle(QtGui.QApplication.translate("TraverseCalcDialog", "Endpoints", None, QtGui.QApplication.UnicodeUTF8))
        self.Endpoints_GroupBox.setObjectName(_fromUtf8("Endpoints_GroupBox"))
        self.StartPoint_ComboBox = QtGui.QComboBox(self.Endpoints_GroupBox)
        self.StartPoint_ComboBox.setGeometry(QtCore.QRect(10, 40, 131, 22))
        self.StartPoint_ComboBox.setObjectName(_fromUtf8("StartPoint_ComboBox"))
        self.StartPoint_Label = QtGui.QLabel(self.Endpoints_GroupBox)
        self.StartPoint_Label.setGeometry(QtCore.QRect(10, 20, 121, 16))
        self.StartPoint_Label.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Start Point", None, QtGui.QApplication.UnicodeUTF8))
        self.StartPoint_Label.setObjectName(_fromUtf8("StartPoint_Label"))
        self.EndPoint_Label = QtGui.QLabel(self.Endpoints_GroupBox)
        self.EndPoint_Label.setGeometry(QtCore.QRect(10, 90, 121, 16))
        self.EndPoint_Label.setText(QtGui.QApplication.translate("TraverseCalcDialog", "End Point", None, QtGui.QApplication.UnicodeUTF8))
        self.EndPoint_Label.setObjectName(_fromUtf8("EndPoint_Label"))
        self.EndPoint_ComboBox = QtGui.QComboBox(self.Endpoints_GroupBox)
        self.EndPoint_ComboBox.setGeometry(QtCore.QRect(10, 110, 131, 22))
        self.EndPoint_ComboBox.setObjectName(_fromUtf8("EndPoint_ComboBox"))
        self.Points_GroupBox = QtGui.QGroupBox(TraverseCalcDialog)
        self.Points_GroupBox.setGeometry(QtCore.QRect(370, 10, 411, 211))
        self.Points_GroupBox.setTitle(QtGui.QApplication.translate("TraverseCalcDialog", "Points", None, QtGui.QApplication.UnicodeUTF8))
        self.Points_GroupBox.setObjectName(_fromUtf8("Points_GroupBox"))
        self.TargetPoints_ListView = QtGui.QListView(self.Points_GroupBox)
        self.TargetPoints_ListView.setGeometry(QtCore.QRect(10, 40, 131, 161))
        self.TargetPoints_ListView.setObjectName(_fromUtf8("TargetPoints_ListView"))
        self.Add_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.Add_PushButton.setGeometry(QtCore.QRect(160, 40, 81, 23))
        self.Add_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Add >", None, QtGui.QApplication.UnicodeUTF8))
        self.Add_PushButton.setObjectName(_fromUtf8("Add_PushButton"))
        self.Remove_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.Remove_PushButton.setGeometry(QtCore.QRect(160, 150, 81, 23))
        self.Remove_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "< Remove", None, QtGui.QApplication.UnicodeUTF8))
        self.Remove_PushButton.setObjectName(_fromUtf8("Remove_PushButton"))
        self.TargetPoints_Label = QtGui.QLabel(self.Points_GroupBox)
        self.TargetPoints_Label.setGeometry(QtCore.QRect(10, 20, 161, 16))
        self.TargetPoints_Label.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Target (Measured) Points", None, QtGui.QApplication.UnicodeUTF8))
        self.TargetPoints_Label.setObjectName(_fromUtf8("TargetPoints_Label"))
        self.OrderPoints_Label = QtGui.QLabel(self.Points_GroupBox)
        self.OrderPoints_Label.setGeometry(QtCore.QRect(270, 20, 151, 16))
        self.OrderPoints_Label.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Order of Traverse Points", None, QtGui.QApplication.UnicodeUTF8))
        self.OrderPoints_Label.setObjectName(_fromUtf8("OrderPoints_Label"))
        self.Calculate_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.Calculate_PushButton.setGeometry(QtCore.QRect(160, 180, 81, 23))
        self.Calculate_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Calculate_PushButton.setObjectName(_fromUtf8("Calculate_PushButton"))
        self.OrderPoints_ListView = QtGui.QListView(self.Points_GroupBox)
        self.OrderPoints_ListView.setGeometry(QtCore.QRect(270, 40, 131, 161))
        self.OrderPoints_ListView.setObjectName(_fromUtf8("OrderPoints_ListView"))
        self.Up_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.Up_PushButton.setGeometry(QtCore.QRect(200, 80, 61, 23))
        self.Up_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Up", None, QtGui.QApplication.UnicodeUTF8))
        self.Up_PushButton.setObjectName(_fromUtf8("Up_PushButton"))
        self.Down_PushButton = QtGui.QPushButton(self.Points_GroupBox)
        self.Down_PushButton.setGeometry(QtCore.QRect(200, 110, 61, 23))
        self.Down_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Down", None, QtGui.QApplication.UnicodeUTF8))
        self.Down_PushButton.setObjectName(_fromUtf8("Down_PushButton"))
        self.Calculate_GroupBox = QtGui.QGroupBox(TraverseCalcDialog)
        self.Calculate_GroupBox.setGeometry(QtCore.QRect(10, 10, 191, 211))
        self.Calculate_GroupBox.setTitle(QtGui.QApplication.translate("TraverseCalcDialog", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Calculate_GroupBox.setFlat(False)
        self.Calculate_GroupBox.setCheckable(False)
        self.Calculate_GroupBox.setObjectName(_fromUtf8("Calculate_GroupBox"))
        self.Calculate_Label = QtGui.QLabel(self.Calculate_GroupBox)
        self.Calculate_Label.setGeometry(QtCore.QRect(10, 20, 201, 16))
        self.Calculate_Label.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Select type of Traverse Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.Calculate_Label.setObjectName(_fromUtf8("Calculate_Label"))
        self.ClosedTrav_RadioButton = QtGui.QRadioButton(self.Calculate_GroupBox)
        self.ClosedTrav_RadioButton.setGeometry(QtCore.QRect(10, 50, 161, 17))
        self.ClosedTrav_RadioButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Closed Traverse", None, QtGui.QApplication.UnicodeUTF8))
        self.ClosedTrav_RadioButton.setObjectName(_fromUtf8("ClosedTrav_RadioButton"))
        self.LoopTrav_RadioButton = QtGui.QRadioButton(self.Calculate_GroupBox)
        self.LoopTrav_RadioButton.setGeometry(QtCore.QRect(10, 80, 161, 20))
        self.LoopTrav_RadioButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Loop Traverse", None, QtGui.QApplication.UnicodeUTF8))
        self.LoopTrav_RadioButton.setObjectName(_fromUtf8("LoopTrav_RadioButton"))
        self.OpenTrav_RadioButton = QtGui.QRadioButton(self.Calculate_GroupBox)
        self.OpenTrav_RadioButton.setGeometry(QtCore.QRect(10, 110, 171, 17))
        self.OpenTrav_RadioButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Open Traverse", None, QtGui.QApplication.UnicodeUTF8))
        self.OpenTrav_RadioButton.setObjectName(_fromUtf8("OpenTrav_RadioButton"))
        self.BeillesztettTrav_RadioButton = QtGui.QRadioButton(self.Calculate_GroupBox)
        self.BeillesztettTrav_RadioButton.setGeometry(QtCore.QRect(10, 140, 201, 17))
        self.BeillesztettTrav_RadioButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Beillesztett Traverse", None, QtGui.QApplication.UnicodeUTF8))
        self.BeillesztettTrav_RadioButton.setObjectName(_fromUtf8("BeillesztettTrav_RadioButton"))
        self.Reset_PushButton = QtGui.QPushButton(TraverseCalcDialog)
        self.Reset_PushButton.setGeometry(QtCore.QRect(570, 400, 91, 23))
        self.Reset_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.Reset_PushButton.setObjectName(_fromUtf8("Reset_PushButton"))
        self.Close_PushButton = QtGui.QPushButton(TraverseCalcDialog)
        self.Close_PushButton.setGeometry(QtCore.QRect(680, 400, 75, 23))
        self.Close_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.Close_PushButton.setObjectName(_fromUtf8("Close_PushButton"))
        self.Result_GroupBox = QtGui.QGroupBox(TraverseCalcDialog)
        self.Result_GroupBox.setGeometry(QtCore.QRect(10, 230, 771, 161))
        self.Result_GroupBox.setTitle(QtGui.QApplication.translate("TraverseCalcDialog", "Result of Calculations", None, QtGui.QApplication.UnicodeUTF8))
        self.Result_GroupBox.setObjectName(_fromUtf8("Result_GroupBox"))
        self.Result_TextBrowser = QtGui.QTextBrowser(self.Result_GroupBox)
        self.Result_TextBrowser.setGeometry(QtCore.QRect(10, 20, 751, 131))
        self.Result_TextBrowser.setObjectName(_fromUtf8("Result_TextBrowser"))
        self.Help_PushButton = QtGui.QPushButton(TraverseCalcDialog)
        self.Help_PushButton.setGeometry(QtCore.QRect(20, 400, 75, 23))
        self.Help_PushButton.setText(QtGui.QApplication.translate("TraverseCalcDialog", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.Help_PushButton.setObjectName(_fromUtf8("Help_PushButton"))

        self.retranslateUi(TraverseCalcDialog)
        QtCore.QMetaObject.connectSlotsByName(TraverseCalcDialog)

    def retranslateUi(self, TraverseCalcDialog):
        pass

