# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'traverse_calc.ui'
#
# Created: Tue Nov 25 01:47:02 2014
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TraverseCalcDialog(object):
    def setupUi(self, TraverseCalcDialog):
        TraverseCalcDialog.setObjectName(_fromUtf8("TraverseCalcDialog"))
        TraverseCalcDialog.resize(754, 456)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TraverseCalcDialog.sizePolicy().hasHeightForWidth())
        TraverseCalcDialog.setSizePolicy(sizePolicy)
        TraverseCalcDialog.setMinimumSize(QtCore.QSize(754, 456))
        TraverseCalcDialog.setMaximumSize(QtCore.QSize(754, 456))
        TraverseCalcDialog.setWindowTitle(_fromUtf8("Traverse Calculations"))
        TraverseCalcDialog.setAccessibleName(_fromUtf8(""))
        TraverseCalcDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.EndpointsGroup = QtGui.QGroupBox(TraverseCalcDialog)
        self.EndpointsGroup.setGeometry(QtCore.QRect(180, 10, 151, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndpointsGroup.sizePolicy().hasHeightForWidth())
        self.EndpointsGroup.setSizePolicy(sizePolicy)
        self.EndpointsGroup.setObjectName(_fromUtf8("EndpointsGroup"))
        self.StartPointComboBox = QtGui.QComboBox(self.EndpointsGroup)
        self.StartPointComboBox.setGeometry(QtCore.QRect(10, 40, 131, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartPointComboBox.sizePolicy().hasHeightForWidth())
        self.StartPointComboBox.setSizePolicy(sizePolicy)
        self.StartPointComboBox.setObjectName(_fromUtf8("StartPointComboBox"))
        self.StartPointLabel = QtGui.QLabel(self.EndpointsGroup)
        self.StartPointLabel.setGeometry(QtCore.QRect(10, 20, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartPointLabel.sizePolicy().hasHeightForWidth())
        self.StartPointLabel.setSizePolicy(sizePolicy)
        self.StartPointLabel.setObjectName(_fromUtf8("StartPointLabel"))
        self.EndPointLabel = QtGui.QLabel(self.EndpointsGroup)
        self.EndPointLabel.setGeometry(QtCore.QRect(10, 90, 121, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndPointLabel.sizePolicy().hasHeightForWidth())
        self.EndPointLabel.setSizePolicy(sizePolicy)
        self.EndPointLabel.setObjectName(_fromUtf8("EndPointLabel"))
        self.EndPointComboBox = QtGui.QComboBox(self.EndpointsGroup)
        self.EndPointComboBox.setGeometry(QtCore.QRect(10, 110, 131, 22))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.EndPointComboBox.sizePolicy().hasHeightForWidth())
        self.EndPointComboBox.setSizePolicy(sizePolicy)
        self.EndPointComboBox.setObjectName(_fromUtf8("EndPointComboBox"))
        self.PointsGroup = QtGui.QGroupBox(TraverseCalcDialog)
        self.PointsGroup.setGeometry(QtCore.QRect(350, 10, 391, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PointsGroup.sizePolicy().hasHeightForWidth())
        self.PointsGroup.setSizePolicy(sizePolicy)
        self.PointsGroup.setObjectName(_fromUtf8("PointsGroup"))
        self.AddButton = QtGui.QPushButton(self.PointsGroup)
        self.AddButton.setGeometry(QtCore.QRect(150, 50, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        self.AddButton.setObjectName(_fromUtf8("AddButton"))
        self.RemoveButton = QtGui.QPushButton(self.PointsGroup)
        self.RemoveButton.setGeometry(QtCore.QRect(150, 180, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveButton.sizePolicy().hasHeightForWidth())
        self.RemoveButton.setSizePolicy(sizePolicy)
        self.RemoveButton.setObjectName(_fromUtf8("RemoveButton"))
        self.TargetPointsLabel = QtGui.QLabel(self.PointsGroup)
        self.TargetPointsLabel.setGeometry(QtCore.QRect(10, 20, 161, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetPointsLabel.sizePolicy().hasHeightForWidth())
        self.TargetPointsLabel.setSizePolicy(sizePolicy)
        self.TargetPointsLabel.setObjectName(_fromUtf8("TargetPointsLabel"))
        self.OrderPointsLabel = QtGui.QLabel(self.PointsGroup)
        self.OrderPointsLabel.setGeometry(QtCore.QRect(250, 20, 151, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderPointsLabel.sizePolicy().hasHeightForWidth())
        self.OrderPointsLabel.setSizePolicy(sizePolicy)
        self.OrderPointsLabel.setObjectName(_fromUtf8("OrderPointsLabel"))
        self.UpButton = QtGui.QPushButton(self.PointsGroup)
        self.UpButton.setGeometry(QtCore.QRect(180, 100, 61, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.UpButton.sizePolicy().hasHeightForWidth())
        self.UpButton.setSizePolicy(sizePolicy)
        self.UpButton.setObjectName(_fromUtf8("UpButton"))
        self.DownButton = QtGui.QPushButton(self.PointsGroup)
        self.DownButton.setGeometry(QtCore.QRect(180, 130, 61, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DownButton.sizePolicy().hasHeightForWidth())
        self.DownButton.setSizePolicy(sizePolicy)
        self.DownButton.setObjectName(_fromUtf8("DownButton"))
        self.TargetList = QtGui.QListWidget(self.PointsGroup)
        self.TargetList.setGeometry(QtCore.QRect(10, 40, 131, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TargetList.sizePolicy().hasHeightForWidth())
        self.TargetList.setSizePolicy(sizePolicy)
        self.TargetList.setObjectName(_fromUtf8("TargetList"))
        self.OrderList = QtGui.QListWidget(self.PointsGroup)
        self.OrderList.setGeometry(QtCore.QRect(250, 40, 131, 171))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OrderList.sizePolicy().hasHeightForWidth())
        self.OrderList.setSizePolicy(sizePolicy)
        self.OrderList.setObjectName(_fromUtf8("OrderList"))
        self.RadioGroup = QtGui.QGroupBox(TraverseCalcDialog)
        self.RadioGroup.setGeometry(QtCore.QRect(10, 10, 151, 221))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadioGroup.sizePolicy().hasHeightForWidth())
        self.RadioGroup.setSizePolicy(sizePolicy)
        self.RadioGroup.setFlat(False)
        self.RadioGroup.setCheckable(False)
        self.RadioGroup.setObjectName(_fromUtf8("RadioGroup"))
        self.ClosedRadio = QtGui.QRadioButton(self.RadioGroup)
        self.ClosedRadio.setGeometry(QtCore.QRect(10, 30, 161, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ClosedRadio.sizePolicy().hasHeightForWidth())
        self.ClosedRadio.setSizePolicy(sizePolicy)
        self.ClosedRadio.setObjectName(_fromUtf8("ClosedRadio"))
        self.buttonGroup = QtGui.QButtonGroup(TraverseCalcDialog)
        self.buttonGroup.setObjectName(_fromUtf8("buttonGroup"))
        self.buttonGroup.addButton(self.ClosedRadio)
        self.LinkRadio = QtGui.QRadioButton(self.RadioGroup)
        self.LinkRadio.setGeometry(QtCore.QRect(10, 60, 161, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkRadio.sizePolicy().hasHeightForWidth())
        self.LinkRadio.setSizePolicy(sizePolicy)
        self.LinkRadio.setObjectName(_fromUtf8("LinkRadio"))
        self.buttonGroup.addButton(self.LinkRadio)
        self.OpenRadio = QtGui.QRadioButton(self.RadioGroup)
        self.OpenRadio.setGeometry(QtCore.QRect(10, 90, 171, 17))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenRadio.sizePolicy().hasHeightForWidth())
        self.OpenRadio.setSizePolicy(sizePolicy)
        self.OpenRadio.setObjectName(_fromUtf8("OpenRadio"))
        self.buttonGroup.addButton(self.OpenRadio)
        self.CloseButton = QtGui.QPushButton(TraverseCalcDialog)
        self.CloseButton.setGeometry(QtCore.QRect(650, 420, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setObjectName(_fromUtf8("CloseButton"))
        self.ResultGroup = QtGui.QGroupBox(TraverseCalcDialog)
        self.ResultGroup.setGeometry(QtCore.QRect(10, 240, 731, 161))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultGroup.sizePolicy().hasHeightForWidth())
        self.ResultGroup.setSizePolicy(sizePolicy)
        self.ResultGroup.setObjectName(_fromUtf8("ResultGroup"))
        self.ResultTextBrowser = QtGui.QTextBrowser(self.ResultGroup)
        self.ResultTextBrowser.setGeometry(QtCore.QRect(10, 20, 711, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResultTextBrowser.sizePolicy().hasHeightForWidth())
        self.ResultTextBrowser.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.ResultTextBrowser.setFont(font)
        self.ResultTextBrowser.setObjectName(_fromUtf8("ResultTextBrowser"))
        self.HelpButton = QtGui.QPushButton(TraverseCalcDialog)
        self.HelpButton.setGeometry(QtCore.QRect(20, 420, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HelpButton.sizePolicy().hasHeightForWidth())
        self.HelpButton.setSizePolicy(sizePolicy)
        self.HelpButton.setObjectName(_fromUtf8("HelpButton"))
        self.CalcButton = QtGui.QPushButton(TraverseCalcDialog)
        self.CalcButton.setGeometry(QtCore.QRect(450, 420, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CalcButton.sizePolicy().hasHeightForWidth())
        self.CalcButton.setSizePolicy(sizePolicy)
        self.CalcButton.setObjectName(_fromUtf8("CalcButton"))
        self.ResetButton = QtGui.QPushButton(TraverseCalcDialog)
        self.ResetButton.setGeometry(QtCore.QRect(550, 420, 81, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ResetButton.sizePolicy().hasHeightForWidth())
        self.ResetButton.setSizePolicy(sizePolicy)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))

        self.retranslateUi(TraverseCalcDialog)
        QtCore.QMetaObject.connectSlotsByName(TraverseCalcDialog)
        TraverseCalcDialog.setTabOrder(self.ClosedRadio, self.LinkRadio)
        TraverseCalcDialog.setTabOrder(self.LinkRadio, self.OpenRadio)
        TraverseCalcDialog.setTabOrder(self.OpenRadio, self.StartPointComboBox)
        TraverseCalcDialog.setTabOrder(self.StartPointComboBox, self.EndPointComboBox)
        TraverseCalcDialog.setTabOrder(self.EndPointComboBox, self.AddButton)
        TraverseCalcDialog.setTabOrder(self.AddButton, self.UpButton)
        TraverseCalcDialog.setTabOrder(self.UpButton, self.DownButton)
        TraverseCalcDialog.setTabOrder(self.DownButton, self.RemoveButton)
        TraverseCalcDialog.setTabOrder(self.RemoveButton, self.ResultTextBrowser)
        TraverseCalcDialog.setTabOrder(self.ResultTextBrowser, self.HelpButton)
        TraverseCalcDialog.setTabOrder(self.HelpButton, self.CalcButton)
        TraverseCalcDialog.setTabOrder(self.CalcButton, self.ResetButton)
        TraverseCalcDialog.setTabOrder(self.ResetButton, self.CloseButton)

    def retranslateUi(self, TraverseCalcDialog):
        self.EndpointsGroup.setTitle(_translate("TraverseCalcDialog", "Endpoints", None))
        self.StartPointLabel.setText(_translate("TraverseCalcDialog", "Start Point", None))
        self.EndPointLabel.setText(_translate("TraverseCalcDialog", "End Point", None))
        self.PointsGroup.setTitle(_translate("TraverseCalcDialog", "Points", None))
        self.AddButton.setText(_translate("TraverseCalcDialog", "Add >", None))
        self.RemoveButton.setText(_translate("TraverseCalcDialog", "< Remove", None))
        self.TargetPointsLabel.setText(_translate("TraverseCalcDialog", "Target Points", None))
        self.OrderPointsLabel.setText(_translate("TraverseCalcDialog", "Order of Points", None))
        self.UpButton.setText(_translate("TraverseCalcDialog", "Up", None))
        self.DownButton.setText(_translate("TraverseCalcDialog", "Down", None))
        self.RadioGroup.setTitle(_translate("TraverseCalcDialog", "Type", None))
        self.ClosedRadio.setToolTip(_translate("TraverseCalcDialog", "Closed (polygonal or loop) traverse starts and finishes on the same known point.", None))
        self.ClosedRadio.setText(_translate("TraverseCalcDialog", "Closed Traverse", None))
        self.LinkRadio.setToolTip(_translate("TraverseCalcDialog", "A closed link traverse joins two known points.", None))
        self.LinkRadio.setText(_translate("TraverseCalcDialog", "Link Traverse", None))
        self.OpenRadio.setToolTip(_translate("TraverseCalcDialog", "An open (free) traverse starts on a known point and finishes on an unknown point.", None))
        self.OpenRadio.setText(_translate("TraverseCalcDialog", "Open Traverse", None))
        self.CloseButton.setText(_translate("TraverseCalcDialog", "Close", None))
        self.ResultGroup.setTitle(_translate("TraverseCalcDialog", "Result of Traverse Calculations", None))
        self.HelpButton.setText(_translate("TraverseCalcDialog", "Help", None))
        self.CalcButton.setText(_translate("TraverseCalcDialog", "Calculate", None))
        self.ResetButton.setText(_translate("TraverseCalcDialog", "Reset", None))

